name: Generar y Publicar Javadoc

on:
  push:
    branches: [ "stable" ] # Solo se ejecuta cuando subes algo a stable

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generar Javadoc con Maven
        run: mvn javadoc:javadoc

      - name: Subir artefacto para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/site/apidocs' # Ruta donde Maven guarda el Javadoc

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
